### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by uRyanxD** [BADnotice/MiningWorld#1]
A tip: instead of making an unnecessary runnable to give the effect use:

 @EventHandler
 public void giveEffect (PlayerChangeWorldEvent e) {
     Player p = e.getPlayer();
     World world = p.getWorld();
     if (world.getName().equals("mina") {
       p.addEffect etc etc
     } else {
      p.removeEffect etc etc
      }
}

**Comment by BADnotice** [comment]
Thank you very much for the tip, it has already been chenged and i will be updating on github soon
