### ISSUE TITLE
Erro ao compilar a src

### ISSUE THREAD

**Issue by Faculoopp** [BADnotice/MiningWorld#6]
Bom dia, tentei comunicar com o senhor pra resolver uma duvida pelo discord mas nao esta funcionando o link do discord.

A minha duvida e a seguinte, ao colocar a source code no eclipse me gera um erro e nao consigo compilar depois, meu discord e Faculoop#8803, se poderia me enviar uma solicitude por la pra eu falar melhor o problema? Muito obrigado, desculpa meu portugues, sou uruguaio.

Obrigado.

**Comment by BADnotice** [comment]
Estarei te chamando no privado do discord
